### ISSUE TITLE
请求支持folia

### ISSUE THREAD

**Issue by xiaoluofa** [meteorOSS/McKook#1]

**Comment by meteorOSS** [comment]
试着直接在 plugin.yml 里添加
`folia-supported: true`

**Comment by xiaoluofa** [comment]
> 试着直接在 plugin.yml 里添加 `folia-supported: true`

有大量报错，聊天同步以及退出加入事件均无法工作
21:56:25 ERROR]: Could not pass event AsyncPlayerChatEvent to McKook v1.0.3-SNAPSHOT
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.handle(CraftScheduler.java:533) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:257) ~[folia-1.20.2.jar:g
it-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:244) ~[folia-1.20.2.jar:g
it-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:189) ~[folia-1.20.2.jar:g
it-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:158) ~[folia-1.20.2.jar:git-Fo
lia-"1e5e215"]
        at com.meteor.mckook.kook.KookBot.sendMessage(KookBot.java:127) ~[McKook-1.0.3-SNAPSHOT.jar:?]
        at com.meteor.mckook.message.sub.PlayerChatMessage.onChat(PlayerChatMessage.java:67) ~[McKook-1.0.3-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor398.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:git-Folia-"1e5e215"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[folia-1.20.2.jar:git-Folia-"1
e5e215"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:416) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:102) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2364) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2494) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$13(ServerGamePacketListenerImpl.java:2194) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by xiaoluofa** [comment]
![Uploading image.png…]()
游戏这边无法发送过去

**Comment by xiaoluofa** [comment]
> 试着直接在 plugin.yml 里添加 `folia-supported: true`
报错
