### ISSUE TITLE
在Kook消息转发到游戏的过程中会出现空指针

### ISSUE THREAD

**Issue by TianmuTNT** [meteorOSS/McKook#5]
具体报错如下

[05:55:40 INFO]: [Kook聊天] 天沐TNT: 111
[05:55:40 WARN]: java.lang.NullPointerException: Cannot invoke "snw.jkook.entity.channel.Channel.getId()" because the return value of "java.util.Map.get(Object)" is null
[05:55:40 WARN]:        at McKook-1.0.3-SNAPSHOT.jar//com.meteor.mckook.message.sub.WhitelistMessage.onLink(WhitelistMessage.java:81)
[05:55:40 WARN]:        at McKook-1.0.3-SNAPSHOT.jar//snw.kookbc.impl.event.EventExecutorFactoryImpl.lambda$create$0(EventExecutorFactoryImpl.java:48)
[05:55:40 WARN]:        at McKook-1.0.3-SNAPSHOT.jar//net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148)
[05:55:40 WARN]:        at McKook-1.0.3-SNAPSHOT.jar//net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107)
[05:55:40 WARN]:        at McKook-1.0.3-SNAPSHOT.jar//snw.kookbc.impl.event.EventManagerImpl.callEvent(EventManagerImpl.java:53)
[05:55:40 WARN]:        at McKook-1.0.3-SNAPSHOT.jar//snw.kookbc.impl.network.ListenerImpl.event0(ListenerImpl.java:155)
[05:55:40 WARN]:        at McKook-1.0.3-SNAPSHOT.jar//snw.kookbc.impl.network.ListenerImpl.event(ListenerImpl.java:108)
[05:55:40 WARN]:        at McKook-1.0.3-SNAPSHOT.jar//snw.kookbc.impl.network.ListenerImpl.lambda$handle$0(ListenerImpl.java:69)
[05:55:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[05:55:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[05:55:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by meteorOSS** [comment]
配置里的频道id是正确的吗?你可以加我qq，我给你看一下

**Comment by TianmuTNT** [comment]
已经按照教程中填写了 如果频道id是错误的也无法转发

**Comment by TianmuTNT** [comment]
emmm如果要看的话 请问需要哪些信息可以帮助解决

**Comment by meteorOSS** [comment]
最近kook要求实名了，机器人是否已经完成实名认证？
